// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bgMU3WxmlbGnjby3fwtQup2nBPbepsY',
    appId: '1:552131556381:web:390848f701a03ca72602f4',
    messagingSenderId: '552131556381',
    projectId: 'movie-1c779',
    authDomain: 'movie-1c779.firebaseapp.com',
    storageBucket: 'movie-1c779.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjziiGRhJJzEvPCVXih9x_nmRFB25-UYQ',
    appId: '1:552131556381:android:267f2001b34d54482602f4',
    messagingSenderId: '552131556381',
    projectId: 'movie-1c779',
    storageBucket: 'movie-1c779.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDim5ELfbRWttloGaEZTQ4_7D4AwNThCGc',
    appId: '1:552131556381:ios:efb9b40e5b8f28ce2602f4',
    messagingSenderId: '552131556381',
    projectId: 'movie-1c779',
    storageBucket: 'movie-1c779.appspot.com',
    iosBundleId: 'com.example.moviesAppCleanArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDim5ELfbRWttloGaEZTQ4_7D4AwNThCGc',
    appId: '1:552131556381:ios:efb9b40e5b8f28ce2602f4',
    messagingSenderId: '552131556381',
    projectId: 'movie-1c779',
    storageBucket: 'movie-1c779.appspot.com',
    iosBundleId: 'com.example.moviesAppCleanArch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bgMU3WxmlbGnjby3fwtQup2nBPbepsY',
    appId: '1:552131556381:web:f8b47123d523ac0f2602f4',
    messagingSenderId: '552131556381',
    projectId: 'movie-1c779',
    authDomain: 'movie-1c779.firebaseapp.com',
    storageBucket: 'movie-1c779.appspot.com',
  );
}
